version: '3'
services:
  linux:
    container_name: ubuntu-linux
    image: ubuntu
    restart: always
    tty: true
    ports:
      - "3000:3000"
      - "2000-2020:2000-2020"
      # - "10000-10100:10000-10100"
    # volumes:
      # - "/Users/amireshaq/DATA/Tutorials/My Tutorials/mediasoup/src:/usr/src"
      # - "/Users/onemo/Desktop/java/My FFFFFFFFFFinal/webRTC/src:/usr/src"
      # - ./data:/var/lib/postgresql/data

      # docker ps
      # docker-compose up -d
      # docker ps