branch-defaults:
  mediasoup4:
    environment: Mediasoup-env
environment-defaults:
  Mediasoup-env:
    branch: null
    repository: null
global:
  application_name: mediasoup
  default_ec2_keyname: simsimhae
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
